#!/usr/bin/env bash

pins=(17 27 22)

for p in "${pins[@]}"; do
    pinctrl set "$p" op
done

finish() {
    for p in "${pins[@]}"; do
        pinctrl set "$p" dl
    done
    exit
}

trap finish SIGINT SIGTERM

output_bits() {
    val=$1
    for i in "${!pins[@]}"; do
        (( (val >> i) & 1 )) && pinctrl set "${pins[i]}" dh || pinctrl set "${pins[i]}" dl
    done
}

while :; do
    for ((n=0; n<8; n++)); do
        output_bits "$n"
        sleep 1
    done
done
